In [1]:
#load libraries w/ iris datset
from sklearn.datasets import load_iris
#load scikit's learn random forest classifier library
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
#np.random.seed(0)

In [2]:
#loading data from the iris_dataet
iris=load_iris()
#create an obj called iris w/ the feature variable
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()#printing first 5 row

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
load_iris()

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThis is a copy of UCI ML iris datasets.\nhttp://archive.ics.uci.edu/ml/datasets/Iris\n\nThe famous Iris database, first used by Sir R.A Fisher\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\nReferences\n----------\n   - Fisher,R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda,R.O., & Hart,P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...\n',
 'data': array([[ 5.1,  3.5,  1.4,  0.2],
        [ 4.9,  3. ,  1.4,  0.2],
        [ 4.7,  3.2,  1.3,  0.2],
        [ 4.6,  3.1,  1.5,  0.2],
        [ 5. ,  3.6,  1.4,  0.2],
        [ 5.4,  3.9,  1.7,  0.4],
        [ 4.6,  3.4,  1.4,  0.3],
        [ 5. ,  3.4,  1.5,  0.2],
        [ 4.4,  2.9,  1.4,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 5.4,  3.7,  1.5,  0.2],
        [ 4.8,  3.4,  1.6,  0.2],
        [ 4.8,  3. ,  1.4,  0.1],
        [ 4.3,  3. ,  1.1,  0.1],
        [ 5.8,  4. ,  1.2,  0.2],
        [ 5.7,  4.4,  1.5,  0.4],
        [ 5.4,  3.9,  1.3,  0.4],
        [ 5.1,  3.5,  1.4,  0.3],
        [ 5.7,  3.8,  1.7,  0.3],
        [ 5.1,  3.8,  1.5,  0.3],
        [ 5.4,  3.4,  1.7,  0.2],
        [ 5.1,  3.7,  1.5,  0.4],
        [ 4.6,  3.6,  1. ,  0.2],
        [ 5.1,  3.3,  1.7,  0.5],
        [ 4.8,  3.4,  1.9,  0.2],
        [ 5. ,  3. ,  1.6,  0.2],
        [ 5. ,  3.4,  1.6,  0.4],
        [ 5.2,  3.5,  1.5,  0.2],
        [ 5.2,  3.4,  1.4,  0.2],
        [ 4.7,  3.2,  1.6,  0.2],
        [ 4.8,  3.1,  1.6,  0.2],
        [ 5.4,  3.4,  1.5,  0.4],
        [ 5.2,  4.1,  1.5,  0.1],
        [ 5.5,  4.2,  1.4,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 5. ,  3.2,  1.2,  0.2],
        [ 5.5,  3.5,  1.3,  0.2],
        [ 4.9,  3.1,  1.5,  0.1],
        [ 4.4,  3. ,  1.3,  0.2],
        [ 5.1,  3.4,  1.5,  0.2],
        [ 5. ,  3.5,  1.3,  0.3],
        [ 4.5,  2.3,  1.3,  0.3],
        [ 4.4,  3.2,  1.3,  0.2],
        [ 5. ,  3.5,  1.6,  0.6],
        [ 5.1,  3.8,  1.9,  0.4],
        [ 4.8,  3. ,  1.4,  0.3],
        [ 5.1,  3.8,  1.6,  0.2],
        [ 4.6,  3.2,  1.4,  0.2],
        [ 5.3,  3.7,  1.5,  0.2],
        [ 5. ,  3.3,  1.4,  0.2],
        [ 7. ,  3.2,  4.7,  1.4],
        [ 6.4,  3.2,  4.5,  1.5],
        [ 6.9,  3.1,  4.9,  1.5],
        [ 5.5,  2.3,  4. ,  1.3],
        [ 6.5,  2.8,  4.6,  1.5],
        [ 5.7,  2.8,  4.5,  1.3],
        [ 6.3,  3.3,  4.7,  1.6],
        [ 4.9,  2.4,  3.3,  1. ],
        [ 6.6,  2.9,  4.6,  1.3],
        [ 5.2,  2.7,  3.9,  1.4],
        [ 5. ,  2. ,  3.5,  1. ],
        [ 5.9,  3. ,  4.2,  1.5],
        [ 6. ,  2.2,  4. ,  1. ],
        [ 6.1,  2.9,  4.7,  1.4],
        [ 5.6,  2.9,  3.6,  1.3],
        [ 6.7,  3.1,  4.4,  1.4],
        [ 5.6,  3. ,  4.5,  1.5],
        [ 5.8,  2.7,  4.1,  1. ],
        [ 6.2,  2.2,  4.5,  1.5],
        [ 5.6,  2.5,  3.9,  1.1],
        [ 5.9,  3.2,  4.8,  1.8],
        [ 6.1,  2.8,  4. ,  1.3],
        [ 6.3,  2.5,  4.9,  1.5],
        [ 6.1,  2.8,  4.7,  1.2],
        [ 6.4,  2.9,  4.3,  1.3],
        [ 6.6,  3. ,  4.4,  1.4],
        [ 6.8,  2.8,  4.8,  1.4],
        [ 6.7,  3. ,  5. ,  1.7],
        [ 6. ,  2.9,  4.5,  1.5],
        [ 5.7,  2.6,  3.5,  1. ],
        [ 5.5,  2.4,  3.8,  1.1],
        [ 5.5,  2.4,  3.7,  1. ],
        [ 5.8,  2.7,  3.9,  1.2],
        [ 6. ,  2.7,  5.1,  1.6],
        [ 5.4,  3. ,  4.5,  1.5],
        [ 6. ,  3.4,  4.5,  1.6],
        [ 6.7,  3.1,  4.7,  1.5],
        [ 6.3,  2.3,  4.4,  1.3],
        [ 5.6,  3. ,  4.1,  1.3],
        [ 5.5,  2.5,  4. ,  1.3],
        [ 5.5,  2.6,  4.4,  1.2],
        [ 6.1,  3. ,  4.6,  1.4],
        [ 5.8,  2.6,  4. ,  1.2],
        [ 5. ,  2.3,  3.3,  1. ],
        [ 5.6,  2.7,  4.2,  1.3],
        [ 5.7,  3. ,  4.2,  1.2],
        [ 5.7,  2.9,  4.2,  1.3],
        [ 6.2,  2.9,  4.3,  1.3],
        [ 5.1,  2.5,  3. ,  1.1],
        [ 5.7,  2.8,  4.1,  1.3],
        [ 6.3,  3.3,  6. ,  2.5],
        [ 5.8,  2.7,  5.1,  1.9],
        [ 7.1,  3. ,  5.9,  2.1],
        [ 6.3,  2.9,  5.6,  1.8],
        [ 6.5,  3. ,  5.8,  2.2],
        [ 7.6,  3. ,  6.6,  2.1],
        [ 4.9,  2.5,  4.5,  1.7],
        [ 7.3,  2.9,  6.3,  1.8],
        [ 6.7,  2.5,  5.8,  1.8],
        [ 7.2,  3.6,  6.1,  2.5],
        [ 6.5,  3.2,  5.1,  2. ],
        [ 6.4,  2.7,  5.3,  1.9],
        [ 6.8,  3. ,  5.5,  2.1],
        [ 5.7,  2.5,  5. ,  2. ],
        [ 5.8,  2.8,  5.1,  2.4],
        [ 6.4,  3.2,  5.3,  2.3],
        [ 6.5,  3. ,  5.5,  1.8],
        [ 7.7,  3.8,  6.7,  2.2],
        [ 7.7,  2.6,  6.9,  2.3],
        [ 6. ,  2.2,  5. ,  1.5],
        [ 6.9,  3.2,  5.7,  2.3],
        [ 5.6,  2.8,  4.9,  2. ],
        [ 7.7,  2.8,  6.7,  2. ],
        [ 6.3,  2.7,  4.9,  1.8],
        [ 6.7,  3.3,  5.7,  2.1],
        [ 7.2,  3.2,  6. ,  1.8],
        [ 6.2,  2.8,  4.8,  1.8],
        [ 6.1,  3. ,  4.9,  1.8],
        [ 6.4,  2.8,  5.6,  2.1],
        [ 7.2,  3. ,  5.8,  1.6],
        [ 7.4,  2.8,  6.1,  1.9],
        [ 7.9,  3.8,  6.4,  2. ],
        [ 6.4,  2.8,  5.6,  2.2],
        [ 6.3,  2.8,  5.1,  1.5],
        [ 6.1,  2.6,  5.6,  1.4],
        [ 7.7,  3. ,  6.1,  2.3],
        [ 6.3,  3.4,  5.6,  2.4],
        [ 6.4,  3.1,  5.5,  1.8],
        [ 6. ,  3. ,  4.8,  1.8],
        [ 6.9,  3.1,  5.4,  2.1],
        [ 6.7,  3.1,  5.6,  2.4],
        [ 6.9,  3.1,  5.1,  2.3],
        [ 5.8,  2.7,  5.1,  1.9],
        [ 6.8,  3.2,  5.9,  2.3],
        [ 6.7,  3.3,  5.7,  2.5],
        [ 6.7,  3. ,  5.2,  2.3],
        [ 6.3,  2.5,  5. ,  1.9],
        [ 6.5,  3. ,  5.2,  2. ],
        [ 6.2,  3.4,  5.4,  2.3],
        [ 5.9,  3. ,  5.1,  1.8]]),
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'target_names': array(['setosa', 'versicolor', 'virginica'],
       dtype='<U10')}

In [4]:
#add a new column w/ the species names, this is what we are going to try to predict
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
#view the top 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [5]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa
10,5.4,3.7,1.5,0.2,setosa
11,4.8,3.4,1.6,0.2,setosa
12,4.8,3.0,1.4,0.1,setosa
13,4.3,3.0,1.1,0.1,setosa
14,5.8,4.0,1.2,0.2,setosa
15,5.7,4.4,1.5,0.4,setosa
16,5.4,3.9,1.3,0.4,setosa
17,5.1,3.5,1.4,0.3,setosa
18,5.7,3.8,1.7,0.3,setosa
19,5.1,3.8,1.5,0.3,setosa
20,5.4,3.4,1.7,0.2,setosa
21,5.1,3.7,1.5,0.4,setosa
22,4.6,3.6,1.0,0.2,setosa
23,5.1,3.3,1.7,0.5,setosa
24,4.8,3.4,1.9,0.2,setosa
25,5.0,3.0,1.6,0.2,setosa
26,5.0,3.4,1.6,0.4,setosa
27,5.2,3.5,1.5,0.2,setosa
28,5.2,3.4,1.4,0.2,setosa
29,4.7,3.2,1.6,0.2,setosa
...,...,...,...,...,...
120,6.9,3.2,5.7,2.3,virginica
121,5.6,2.8,4.9,2.0,virginica
122,7.7,2.8,6.7,2.0,virginica
123,6.3,2.7,4.9,1.8,virginica
124,6.7,3.3,5.7,2.1,virginica
125,7.2,3.2,6.0,1.8,virginica
126,6.2,2.8,4.8,1.8,virginica
127,6.1,3.0,4.9,1.8,virginica
128,6.4,2.8,5.6,2.1,virginica
129,7.2,3.0,5.8,1.6,virginica
130,7.4,2.8,6.1,1.9,virginica
131,7.9,3.8,6.4,2.0,virginica
132,6.4,2.8,5.6,2.2,virginica
133,6.3,2.8,5.1,1.5,virginica
134,6.1,2.6,5.6,1.4,virginica
135,7.7,3.0,6.1,2.3,virginica
136,6.3,3.4,5.6,2.4,virginica
137,6.4,3.1,5.5,1.8,virginica
138,6.0,3.0,4.8,1.8,virginica
139,6.9,3.1,5.4,2.1,virginica
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
142,5.8,2.7,5.1,1.9,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [6]:
df.columns[:5]

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [7]:
#the above dataset is used to construct our classifier.
#creating empty dataFrame
flower=pd.DataFrame()
#now we shall create a new person for whom we know
#their feature values but not the gender.
#or goul is to predict the gender
#creating the feature values for this single row
flower['sepal length (cm)']=[5.4]
flower['sepal width (cm)']=[3.2]
flower['petal length (cm)']=[1.0]
flower['petal width (cm)']=[0.1]
#view the data
flower

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                4.0               3.0                1.0               0.1

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [9]:
#calculating the prior values
#we shall calculate the prior for both male and feamles genders
#prior can be either constants or probalitydistributions
#In our example is the simply the probability of being the gender
#number of setosa
n_setosa=df['species'][df['species']=='setosa'].count()

#number of versicolor
n_versicolor=df['species'][df['species']=='versicolor'].count()

#number of virginica
n_virginica=df['species'][df['species']=='virginica'].count()


#total rows
total_people = df['species'].count()
print('count of setosa  = {}, versicolor = {} , virginica = {} and all persons = {} '.format(n_setosa,n_versicolor,n_virginica,total_people))

count of setosa  = 50, versicolor = 50 , virginica = 50 and all persons = 150

In [10]:
#number of male divide by the tota number of candidates
p_setosa=n_setosa/total_people #prior for male

#no. of feamles divided by the toatl number of candidates
p_versicolor=n_versicolor/total_people #prior foe female


#no. of feamles divided by the toatl number of candidates
p_virginica=n_virginica/total_people #prior foe female

print('prior for setosa = {} and versicolor = {} and virginica={}'.format(p_setosa,p_versicolor,p_virginica))

prior for setosa = 0.3333333333333333 and versicolor = 0.3333333333333333 and virginica=0.3333333333333333

In [11]:
#now doing group by gender and calculating the mean of each feature
df_means=df.groupby('species').mean()

#view the values
df_means

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
setosa,5.006,3.418,1.464,0.244
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026

In [12]:
#now doing group by gender and calculate variance of each feature 
df_varience=df.groupby('species').var()

#view the values
df_varience

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
setosa,0.124249,0.145180,0.030106,0.011494
versicolor,0.266433,0.098469,0.220816,0.039106
virginica,0.404343,0.104004,0.304588,0.075433

In [13]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [14]:
#mean for setosa candidates
setosa_sepallen_mean  = df_means['sepal length (cm)'][df_means.index=='setosa'].values[0]
setosa_sepalwid_mean  = df_means['sepal width (cm)'][df_means.index=='setosa'].values[0]
setosa_petallen_mean  = df_means['petal length (cm)'][df_means.index=='setosa'].values[0]
setosa_petalwid_mean  = df_means['petal width (cm)'][df_means.index=='setosa'].values[0]

#print('so mean male height= {}, weight = {}, footsize = {}'.format(male_height_mean,male_weight_mean,male_footsize_mean))

In [15]:
#mean for versicolor candidates
versicolor_sepallen_mean  = df_means['sepal length (cm)'][df_means.index=='versicolor'].values[0]
versicolor_sepalwid_mean  = df_means['sepal width (cm)'][df_means.index=='versicolor'].values[0]
versicolor_petallen_mean  = df_means['petal length (cm)'][df_means.index=='versicolor'].values[0]
versicolor_petalwid_mean  = df_means['petal width (cm)'][df_means.index=='versicolor'].values[0]

#print('so mean male height= {}, weight = {}, footsize = {}'.format(male_height_mean,male_weight_mean,male_footsize_mean))

In [16]:
#mean for virginica candidates
virginica_sepallen_mean  = df_means['sepal length (cm)'][df_means.index=='virginica'].values[0]
virginica_sepalwid_mean  = df_means['sepal width (cm)'][df_means.index=='virginica'].values[0]
virginica_petallen_mean  = df_means['petal length (cm)'][df_means.index=='virginica'].values[0]
virginica_petalwid_mean  = df_means['petal width (cm)'][df_means.index=='virginica'].values[0]

#print('so mean male height= {}, weight = {}, footsize = {}'.format(male_height_mean,male_weight_mean,male_footsize_mean))

In [17]:
#varience for male candidates
setosa_sepallen_varience  = df_varience['sepal length (cm)'][df_varience.index=='setosa'].values[0]
setosa_sepalwid_varience  = df_varience['sepal width (cm)'][df_varience.index=='setosa'].values[0]
setosa_petallen_varience  = df_varience['petal length (cm)'][df_varience.index=='setosa'].values[0]
setosa_petalwid_varience  = df_varience['petal width (cm)'][df_varience.index=='setosa'].values[0]
#print('so varience male height= {}, weight = {}, footsize = {}'.format(male_height_varience,male_weight_varience,male_footsize_varience))

In [18]:
#varience for male candidates
versicolor_sepallen_varience  = df_varience['sepal length (cm)'][df_varience.index=='versicolor'].values[0]
versicolor_sepalwid_varience  = df_varience['sepal width (cm)'][df_varience.index=='versicolor'].values[0]
versicolor_petallen_varience  = df_varience['petal length (cm)'][df_varience.index=='versicolor'].values[0]
versicolor_petalwid_varience  = df_varience['petal width (cm)'][df_varience.index=='versicolor'].values[0]
#print('so varience male height= {}, weight = {}, footsize = {}'.format(male_height_varience,male_weight_varience,male_footsize_varience))

In [19]:
#varience for male candidates
virginica_sepallen_varience  = df_varience['sepal length (cm)'][df_varience.index=='virginica'].values[0]
virginica_sepalwid_varience  = df_varience['sepal width (cm)'][df_varience.index=='virginica'].values[0]
virginica_petallen_varience  = df_varience['petal length (cm)'][df_varience.index=='virginica'].values[0]
virginica_petalwid_varience  = df_varience['petal width (cm)'][df_varience.index=='virginica'].values[0]
#print('so varience male height= {}, weight = {}, footsize = {}'.format(male_height_varience,male_weight_varience,male_footsize_varience))

In [20]:
#writing one user defined functions which will calculate p(X/Y)

def p_x_given_y (x, mean_y, var_y):#prob of x given y
    #input ting the arguments into the probability density functin
    p=(1/np.sqrt(2*np.pi*var_y))*np.exp(-(x-mean_y)**2/(2*var_y))
    
    #returning the value of p
    return p

In [21]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='<U10')

In [22]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [23]:
#now appling bayes classifier to a new data point

#we are calculating numerator part of the posterior of the male if unclassified observation is male
num_posterior_setosa=p_setosa *\
p_x_given_y(flower['sepal length (cm)'][0],setosa_sepallen_mean,setosa_sepallen_varience)\
*p_x_given_y(flower['sepal width (cm)'][0],setosa_sepalwid_mean,setosa_sepalwid_varience)\
*p_x_given_y(flower['petal length (cm)'][0],setosa_petallen_mean,setosa_petallen_varience)\
*p_x_given_y(flower['petal width (cm)'][0],setosa_petalwid_mean,setosa_petalwid_varience)

num_posterior_setosa

0.00035824812183758188

In [24]:
#now appling bayes classifier to a new data point

#we are calculating numerator part of the posterior of the male if unclassified observation is male
num_posterior_versicolor=p_versicolor *\
p_x_given_y(flower['sepal length (cm)'][0],versicolor_sepallen_mean,versicolor_sepallen_varience)\
*p_x_given_y(flower['sepal width (cm)'][0],versicolor_sepalwid_mean,versicolor_sepalwid_varience)\
*p_x_given_y(flower['petal length (cm)'][0],versicolor_petallen_mean,versicolor_petallen_varience)\
*p_x_given_y(flower['petal width (cm)'][0],versicolor_petalwid_mean,versicolor_petalwid_varience)

num_posterior_versicolor

6.0293743958536177e-23

In [25]:
#now appling bayes classifier to a new data point

#we are calculating numerator part of the posterior of the male if unclassified observation is male
num_posterior_virginica=p_virginica *\
p_x_given_y(flower['sepal length (cm)'][0],virginica_sepallen_mean,virginica_sepallen_varience)\
*p_x_given_y(flower['sepal width (cm)'][0],virginica_sepalwid_mean,virginica_sepalwid_varience)\
*p_x_given_y(flower['petal length (cm)'][0],virginica_petallen_mean,virginica_petallen_varience)\
*p_x_given_y(flower['petal width (cm)'][0],virginica_petalwid_mean,virginica_petalwid_varience)

num_posterior_virginica

2.4263826351184344e-30

In [26]:
if(num_posterior_setosa>num_posterior_versicolor):
    if(num_posterior_setosa>num_posterior_virginica):
        print("it is a setosa")
    else:
        print("it is a virginica")
else:
    if(num_posterior_versicolor>num_posterior_virginica):
        print("it is a versicolor")
    else:
        print("it is a virginica")

it is a setosa